// lib/resume-templates/template-data.ts
import type { ResumeTemplate } from './type';

export const templates: ResumeTemplate[] = [
  // ───────────────────────── Modern ─────────────────────────
  {
    id: 'modern-pro',
    name: 'Modern Pro',
    category: 'modern',
    colors: ['blue', 'purple', 'teal'],
    layout: 'two-column',
    preview: '/templates/modern-pro.png',
    description: 'Clean modern design with accent sidebar and professional typography',
    features: ['ATS-friendly', 'Skill rating bars', 'Project showcase', 'QR code ready'],
    bestFor: ['Tech professionals', 'Mid-senior roles', 'Startup applications'],
    atsScore: 92,
    popularity: 5,
    isPremium: false,
    config: {
      type: 'modern', font: 'inter', colorScheme: 'blue', fontSize: 'medium', spacing: 'normal',
      showIcons: true, showBorders: true,
      sections: { experience: true, education: true, skills: true, projects: true, certifications: false, languages: false },
      layout_type: 'two-column',
    },
  },
  {
    id: 'sleek-executive',
    name: 'Sleek Executive',
    category: 'modern',
    colors: ['blue', 'gray', 'black'],
    layout: 'single-column',
    preview: '/templates/sleek-executive.png',
    description: 'Bold headers with elegant spacing for executive presence',
    features: ['Executive summary', 'Achievement-focused', 'Board-ready format', 'Clean lines'],
    bestFor: ['C-suite', 'VP/Director level', 'Consulting'],
    atsScore: 88,
    popularity: 4,
    isPremium: true,
    config: {
      type: 'classic', font: 'playfair', colorScheme: 'gray', fontSize: 'large', spacing: 'spacious',
      showIcons: false, showBorders: true,
      sections: { experience: true, education: true, skills: false, projects: false, certifications: true, languages: false },
      layout_type: 'single-column',
    },
  },
  {
    id: 'tech-pioneer',
    name: 'Tech Pioneer',
    category: 'modern',
    colors: ['blue', 'green', 'purple'],
    layout: 'sidebar',
    preview: '/templates/tech-pioneer.png',
    description: 'Sidebar layout with tech stack emphasis and project highlights',
    features: ['GitHub integration', 'Tech stack matrix', 'Project timeline', 'Cert badges'],
    bestFor: ['Software engineers', 'DevOps', 'Full-stack developers'],
    atsScore: 85,
    popularity: 5,
    isPremium: false,
    config: {
      type: 'modern', font: 'mono', colorScheme: 'green', fontSize: 'small', spacing: 'compact',
      showIcons: true, showBorders: true,
      sections: { experience: true, education: true, skills: true, projects: true, certifications: true, languages: false },
      layout_type: 'sidebar',
    },
  },
  {
    id: 'gradient-pro',
    name: 'Gradient Pro',
    category: 'modern',
    colors: ['purple', 'blue', 'teal'],
    layout: 'hybrid',
    preview: '/templates/gradient-pro.png',
    description: 'Modern gradient accents with clean two-panel layout',
    features: ['Gradient headers', 'Skill cloud', 'Timeline view', 'Icon support'],
    bestFor: ['Designers', 'Product managers', 'Marketing'],
    atsScore: 82,
    popularity: 4,
    isPremium: true,
    config: {
      type: 'modern', font: 'inter', colorScheme: 'purple', fontSize: 'medium', spacing: 'normal',
      showIcons: true, showBorders: false,
      sections: { experience: true, education: true, skills: true, projects: true, certifications: false, languages: true },
      layout_type: 'hybrid',
    },
  },
  {
    id: 'minimal-edge',
    name: 'Minimal Edge',
    category: 'modern',
    colors: ['black', 'gray', 'blue'],
    layout: 'single-column',
    preview: '/templates/minimal-edge.png',
    description: 'Ultra-minimal with strategic color accents for key information',
    features: ['Whitespace focus', 'Subtle accents', 'Reading-optimized', 'Print-perfect'],
    bestFor: ['Academics', 'Writers', 'Researchers'],
    atsScore: 95,
    popularity: 3,
    isPremium: false,
    config: {
      type: 'minimal', font: 'calibri', colorScheme: 'gray', fontSize: 'small', spacing: 'spacious',
      showIcons: false, showBorders: false,
      sections: { experience: true, education: true, skills: false, projects: false, certifications: false, languages: false },
      layout_type: 'single-column',
    },
  },

  // ───────────────────────── Classic ─────────────────────────
  {
    id: 'timeless-professional',
    name: 'Timeless Professional',
    category: 'classic',
    colors: ['black', 'blue', 'gray'],
    layout: 'single-column',
    preview: '/templates/timeless.png',
    description: 'Traditional resume format trusted by Fortune 500 companies',
    features: ['Standard format', 'Clear hierarchy', 'Print-optimized', 'Email-ready'],
    bestFor: ['Traditional industries', 'Finance', 'Legal'],
    atsScore: 98,
    popularity: 5,
    isPremium: false,
    config: {
      type: 'classic', font: 'roboto', colorScheme: 'blue', fontSize: 'medium', spacing: 'normal',
      showIcons: false, showBorders: true,
      sections: { experience: true, education: true, skills: true, projects: false, certifications: true, languages: false },
      layout_type: 'single-column',
    },
  },
  {
    id: 'wall-street',
    name: 'Wall Street',
    category: 'classic',
    colors: ['black', 'gray', 'blue'],
    layout: 'single-column',
    preview: '/templates/wall-street.png',
    description: 'Conservative, high-impact design for finance professionals',
    features: ['Deal highlights', 'Revenue impact', 'Bulge bracket format', 'Conservative'],
    bestFor: ['Investment banking', 'Private equity', 'Hedge funds'],
    atsScore: 97,
    popularity: 4,
    isPremium: true,
    config: {
      type: 'classic', font: 'calibri', colorScheme: 'gray', fontSize: 'small', spacing: 'compact',
      showIcons: false, showBorders: true,
      sections: { experience: true, education: true, skills: true, projects: false, certifications: true, languages: false },
      layout_type: 'single-column',
    },
  },
  {
    id: 'heritage-standard',
    name: 'Heritage Standard',
    category: 'classic',
    colors: ['black', 'gray'],
    layout: 'single-column',
    preview: '/templates/heritage-standard.png',
    description: 'Understated, letterhead-style format built for conservative industries',
    features: ['Letterhead header', 'Serif hierarchy', 'Dense but readable', 'Print-first'],
    bestFor: ['Government', 'Insurance', 'Public sector'],
    atsScore: 96,
    popularity: 3,
    isPremium: false,
    config: {
      type: 'classic', font: 'roboto', colorScheme: 'black', fontSize: 'medium', spacing: 'normal',
      showIcons: false, showBorders: true,
      sections: { experience: true, education: true, skills: true, projects: false, certifications: true, languages: false },
      layout_type: 'single-column',
    },
  },
  {
    id: 'corporate-classic',
    name: 'Corporate Classic',
    category: 'classic',
    colors: ['blue', 'gray'],
    layout: 'two-column',
    preview: '/templates/corporate-classic.png',
    description: 'Two-column classic layout balancing structure with easy scanning',
    features: ['Sidebar contact block', 'Clear section dividers', 'Balanced whitespace'],
    bestFor: ['Operations', 'Corporate roles', 'Middle management'],
    atsScore: 91,
    popularity: 4,
    isPremium: false,
    config: {
      type: 'classic', font: 'calibri', colorScheme: 'blue', fontSize: 'medium', spacing: 'normal',
      showIcons: false, showBorders: true,
      sections: { experience: true, education: true, skills: true, projects: false, certifications: true, languages: true },
      layout_type: 'two-column',
    },
  },

  // ───────────────────────── Creative ─────────────────────────
  {
    id: 'design-studio',
    name: 'Design Studio',
    category: 'creative',
    colors: ['purple', 'orange', 'teal'],
    layout: 'two-column',
    preview: '/templates/design-studio.png',
    description: 'Visually stunning design for creative professionals',
    features: ['Portfolio integration', 'Color psychology', 'Visual hierarchy', 'Brand personality'],
    bestFor: ['Graphic designers', 'Art directors', 'Creative directors'],
    atsScore: 65,
    popularity: 5,
    isPremium: false,
    config: {
      type: 'modern', font: 'playfair', colorScheme: 'purple', fontSize: 'large', spacing: 'spacious',
      showIcons: true, showBorders: false,
      sections: { experience: true, education: true, skills: true, projects: true, certifications: true, languages: true },
      layout_type: 'two-column',
    },
  },
  {
    id: 'portfolio-showcase',
    name: 'Portfolio Showcase',
    category: 'creative',
    colors: ['orange', 'purple', 'black'],
    layout: 'hybrid',
    preview: '/templates/portfolio-showcase.png',
    description: 'Project-first layout that leads with visual work samples',
    features: ['Project grid', 'Case study callouts', 'Bold typography', 'Link ready'],
    bestFor: ['Product designers', 'Photographers', 'Illustrators'],
    atsScore: 60,
    popularity: 4,
    isPremium: true,
    config: {
      type: 'modern', font: 'playfair', colorScheme: 'orange', fontSize: 'large', spacing: 'spacious',
      showIcons: true, showBorders: false,
      sections: { experience: true, education: false, skills: true, projects: true, certifications: false, languages: false },
      layout_type: 'hybrid',
    },
  },
  {
    id: 'artistic-vision',
    name: 'Artistic Vision',
    category: 'creative',
    colors: ['teal', 'purple', 'red'],
    layout: 'sidebar',
    preview: '/templates/artistic-vision.png',
    description: 'Expressive sidebar template with a strong color-blocked identity',
    features: ['Color-blocked sidebar', 'Statement headline', 'Skill tags', 'Awards ribbon'],
    bestFor: ['Illustrators', 'Fashion design', 'Brand designers'],
    atsScore: 62,
    popularity: 3,
    isPremium: true,
    config: {
      type: 'modern', font: 'playfair', colorScheme: 'teal', fontSize: 'medium', spacing: 'spacious',
      showIcons: true, showBorders: false,
      sections: { experience: true, education: true, skills: true, projects: true, certifications: false, languages: true },
      layout_type: 'sidebar',
    },
  },
  {
    id: 'brand-storyteller',
    name: 'Brand Storyteller',
    category: 'creative',
    colors: ['red', 'orange', 'black'],
    layout: 'two-column',
    preview: '/templates/brand-storyteller.png',
    description: 'Narrative-driven layout for marketers who sell their own story',
    features: ['Personal tagline', 'Campaign highlights', 'Metrics callouts', 'Icon accents'],
    bestFor: ['Brand marketers', 'Content strategists', 'Copywriters'],
    atsScore: 70,
    popularity: 4,
    isPremium: false,
    config: {
      type: 'modern', font: 'inter', colorScheme: 'red', fontSize: 'medium', spacing: 'normal',
      showIcons: true, showBorders: false,
      sections: { experience: true, education: true, skills: true, projects: true, certifications: false, languages: false },
      layout_type: 'two-column',
    },
  },

  // ───────────────────────── Minimal ─────────────────────────
  {
    id: 'pure-minimal',
    name: 'Pure Minimal',
    category: 'minimal',
    colors: ['black', 'gray', 'blue'],
    layout: 'single-column',
    preview: '/templates/pure-minimal.png',
    description: 'Stripped-down design focusing purely on content',
    features: ['Zero clutter', 'Maximum readability', 'Fast scanning', 'Universal appeal'],
    bestFor: ['Any professional', 'ATS optimization', 'Quick applications'],
    atsScore: 99,
    popularity: 5,
    isPremium: false,
    config: {
      type: 'minimal', font: 'inter', colorScheme: 'gray', fontSize: 'medium', spacing: 'normal',
      showIcons: false, showBorders: false,
      sections: { experience: true, education: true, skills: true, projects: false, certifications: false, languages: false },
      layout_type: 'single-column',
    },
  },
  {
    id: 'quiet-clarity',
    name: 'Quiet Clarity',
    category: 'minimal',
    colors: ['gray', 'black'],
    layout: 'single-column',
    preview: '/templates/quiet-clarity.png',
    description: 'Generous whitespace and a single hairline rule per section',
    features: ['Hairline dividers', 'Restrained type scale', 'Distraction-free'],
    bestFor: ['Researchers', 'Analysts', 'Early-career professionals'],
    atsScore: 97,
    popularity: 3,
    isPremium: false,
    config: {
      type: 'minimal', font: 'calibri', colorScheme: 'gray', fontSize: 'small', spacing: 'spacious',
      showIcons: false, showBorders: true,
      sections: { experience: true, education: true, skills: false, projects: false, certifications: false, languages: false },
      layout_type: 'single-column',
    },
  },
  {
    id: 'essential-mono',
    name: 'Essential Mono',
    category: 'minimal',
    colors: ['black', 'gray'],
    layout: 'single-column',
    preview: '/templates/essential-mono.png',
    description: 'Monospaced, terminal-inspired minimalism for a technical audience',
    features: ['Monospace type', 'Compact grid', 'No color dependency'],
    bestFor: ['Engineers', 'Systems roles', 'Open-source contributors'],
    atsScore: 94,
    popularity: 3,
    isPremium: false,
    config: {
      type: 'minimal', font: 'mono', colorScheme: 'black', fontSize: 'small', spacing: 'compact',
      showIcons: false, showBorders: false,
      sections: { experience: true, education: true, skills: true, projects: false, certifications: false, languages: false },
      layout_type: 'single-column',
    },
  },
  {
    id: 'paperwhite',
    name: 'Paperwhite',
    category: 'minimal',
    colors: ['gray', 'blue'],
    layout: 'single-column',
    preview: '/templates/paperwhite.png',
    description: 'Paper-inspired minimal template that reads like a well-set letter',
    features: ['Letter-style header', 'Single accent rule', 'Print-perfect margins'],
    bestFor: ['Academics', 'Grant applications', 'Formal industries'],
    atsScore: 98,
    popularity: 3,
    isPremium: false,
    config: {
      type: 'minimal', font: 'roboto', colorScheme: 'gray', fontSize: 'medium', spacing: 'spacious',
      showIcons: false, showBorders: false,
      sections: { experience: true, education: true, skills: false, projects: false, certifications: true, languages: false },
      layout_type: 'single-column',
    },
  },

  // ───────────────────────── Tech ─────────────────────────
  {
    id: 'fullstack-developer',
    name: 'Full Stack Developer',
    category: 'tech',
    colors: ['green', 'blue', 'purple'],
    layout: 'sidebar',
    preview: '/templates/fullstack.png',
    description: 'Tech-focused resume with stack emphasis and GitHub integration',
    features: ['GitHub stats', 'Stack matrix', 'Code snippets', 'Deployment stats'],
    bestFor: ['Full stack devs', 'Web developers', 'Software engineers'],
    atsScore: 88,
    popularity: 5,
    isPremium: false,
    config: {
      type: 'modern', font: 'mono', colorScheme: 'green', fontSize: 'small', spacing: 'compact',
      showIcons: true, showBorders: true,
      sections: { experience: true, education: true, skills: true, projects: true, certifications: true, languages: false },
      layout_type: 'sidebar',
    },
  },
  {
    id: 'data-science-pro',
    name: 'Data Science Pro',
    category: 'tech',
    colors: ['blue', 'purple', 'teal'],
    layout: 'two-column',
    preview: '/templates/data-science.png',
    description: 'Data visualization inspired layout for data professionals',
    features: ['Project metrics', 'Model performance', 'Data pipeline', 'Visualization'],
    bestFor: ['Data scientists', 'ML engineers', 'Analytics leads'],
    atsScore: 86,
    popularity: 5,
    isPremium: false,
    config: {
      type: 'modern', font: 'inter', colorScheme: 'blue', fontSize: 'medium', spacing: 'normal',
      showIcons: true, showBorders: true,
      sections: { experience: true, education: true, skills: true, projects: true, certifications: false, languages: false },
      layout_type: 'two-column',
    },
  },
  {
    id: 'devops-architect',
    name: 'DevOps Architect',
    category: 'tech',
    colors: ['orange', 'blue', 'green'],
    layout: 'hybrid',
    preview: '/templates/devops.png',
    description: 'Infrastructure-focused resume for DevOps and cloud professionals',
    features: ['Cloud platforms', 'CI/CD pipelines', 'Infrastructure as code', 'Monitoring'],
    bestFor: ['DevOps engineers', 'Cloud architects', 'SRE'],
    atsScore: 84,
    popularity: 4,
    isPremium: false,
    config: {
      type: 'modern', font: 'roboto', colorScheme: 'orange', fontSize: 'small', spacing: 'compact',
      showIcons: true, showBorders: true,
      sections: { experience: true, education: true, skills: true, projects: true, certifications: true, languages: false },
      layout_type: 'hybrid',
    },
  },
  {
    id: 'cybersecurity-expert',
    name: 'Cybersecurity Expert',
    category: 'tech',
    colors: ['red', 'black', 'gray'],
    layout: 'single-column',
    preview: '/templates/security.png',
    description: 'Security-focused resume with certifications and compliance emphasis',
    features: ['Certifications', 'Security tools', 'Compliance frameworks', 'Incident response'],
    bestFor: ['Security engineers', 'CISOs', 'Penetration testers'],
    atsScore: 89,
    popularity: 4,
    isPremium: true,
    config: {
      type: 'classic', font: 'calibri', colorScheme: 'red', fontSize: 'medium', spacing: 'normal',
      showIcons: false, showBorders: true,
      sections: { experience: true, education: true, skills: true, projects: false, certifications: true, languages: false },
      layout_type: 'single-column',
    },
  },
  {
    id: 'cloud-native',
    name: 'Cloud Native',
    category: 'tech',
    colors: ['blue', 'teal'],
    layout: 'sidebar',
    preview: '/templates/cloud-native.png',
    description: 'Sidebar template built around cloud platforms and certifications',
    features: ['Platform badges', 'Architecture highlights', 'Uptime metrics'],
    bestFor: ['Cloud engineers', 'Platform engineers', 'Solutions architects'],
    atsScore: 87,
    popularity: 4,
    isPremium: false,
    config: {
      type: 'modern', font: 'inter', colorScheme: 'blue', fontSize: 'small', spacing: 'normal',
      showIcons: true, showBorders: true,
      sections: { experience: true, education: true, skills: true, projects: true, certifications: true, languages: false },
      layout_type: 'sidebar',
    },
  },
  {
    id: 'mobile-architect',
    name: 'Mobile Architect',
    category: 'tech',
    colors: ['purple', 'blue'],
    layout: 'two-column',
    preview: '/templates/mobile-architect.png',
    description: 'App-store inspired layout for iOS and Android engineers',
    features: ['App showcase', 'Store rating callouts', 'Release timeline'],
    bestFor: ['iOS developers', 'Android developers', 'Mobile leads'],
    atsScore: 85,
    popularity: 3,
    isPremium: false,
    config: {
      type: 'modern', font: 'inter', colorScheme: 'purple', fontSize: 'medium', spacing: 'normal',
      showIcons: true, showBorders: true,
      sections: { experience: true, education: true, skills: true, projects: true, certifications: false, languages: false },
      layout_type: 'two-column',
    },
  },
  {
    id: 'ai-ml-engineer',
    name: 'AI/ML Engineer',
    category: 'tech',
    colors: ['teal', 'purple', 'blue'],
    layout: 'hybrid',
    preview: '/templates/ai-ml-engineer.png',
    description: 'Research-meets-product layout for applied ML practitioners',
    features: ['Publications list', 'Model benchmarks', 'Research highlights'],
    bestFor: ['ML engineers', 'Applied scientists', 'AI researchers'],
    atsScore: 83,
    popularity: 5,
    isPremium: true,
    config: {
      type: 'modern', font: 'mono', colorScheme: 'teal', fontSize: 'small', spacing: 'normal',
      showIcons: true, showBorders: true,
      sections: { experience: true, education: true, skills: true, projects: true, certifications: false, languages: false },
      layout_type: 'hybrid',
    },
  },

  // ───────────────────────── Executive ─────────────────────────
  {
    id: 'boardroom-ready',
    name: 'Boardroom Ready',
    category: 'executive',
    colors: ['black', 'blue', 'gray'],
    layout: 'single-column',
    preview: '/templates/boardroom.png',
    description: 'Commanding presence for C-suite and board-level positions',
    features: ['Executive summary', 'Board experience', 'P&L ownership', 'Strategic vision'],
    bestFor: ['CEOs', 'CFOs', 'Board members'],
    atsScore: 85,
    popularity: 5,
    isPremium: true,
    config: {
      type: 'classic', font: 'playfair', colorScheme: 'blue', fontSize: 'large', spacing: 'spacious',
      showIcons: false, showBorders: true,
      sections: { experience: true, education: true, skills: false, projects: false, certifications: true, languages: true },
      layout_type: 'single-column',
    },
  },
  {
    id: 'chairman-select',
    name: 'Chairman Select',
    category: 'executive',
    colors: ['black', 'gray'],
    layout: 'single-column',
    preview: '/templates/chairman-select.png',
    description: 'A restrained, letterhead-driven format for board and advisory roles',
    features: ['Advisory board list', 'Governance highlights', 'Understated typography'],
    bestFor: ['Board members', 'Advisors', 'Non-executive directors'],
    atsScore: 90,
    popularity: 3,
    isPremium: true,
    config: {
      type: 'classic', font: 'playfair', colorScheme: 'black', fontSize: 'large', spacing: 'spacious',
      showIcons: false, showBorders: true,
      sections: { experience: true, education: true, skills: false, projects: false, certifications: true, languages: false },
      layout_type: 'single-column',
    },
  },
  {
    id: 'founder-focus',
    name: 'Founder Focus',
    category: 'executive',
    colors: ['blue', 'black'],
    layout: 'hybrid',
    preview: '/templates/founder-focus.png',
    description: 'A founder-story-first layout that leads with company outcomes',
    features: ['Company outcomes', 'Funding milestones', 'Leadership narrative'],
    bestFor: ['Founders', 'Startup executives', 'General managers'],
    atsScore: 84,
    popularity: 4,
    isPremium: true,
    config: {
      type: 'modern', font: 'inter', colorScheme: 'blue', fontSize: 'medium', spacing: 'normal',
      showIcons: true, showBorders: true,
      sections: { experience: true, education: true, skills: true, projects: true, certifications: false, languages: false },
      layout_type: 'hybrid',
    },
  },

  // ───────────────────────── ATS ─────────────────────────
  {
    id: 'universal-ats',
    name: 'Universal ATS',
    category: 'ats',
    colors: ['black', 'gray', 'blue'],
    layout: 'single-column',
    preview: '/templates/universal-ats.png',
    description: 'Plain single-column format built to parse cleanly in any ATS',
    features: ['No tables or columns', 'Standard section headers', 'Parser-tested'],
    bestFor: ['High-volume applications', 'Corporate roles', 'Government jobs'],
    atsScore: 99,
    popularity: 5,
    isPremium: false,
    config: {
      type: 'minimal', font: 'calibri', colorScheme: 'black', fontSize: 'medium', spacing: 'normal',
      showIcons: false, showBorders: false,
      sections: { experience: true, education: true, skills: true, projects: false, certifications: true, languages: false },
      layout_type: 'single-column',
    },
  },
  {
    id: 'keyword-optimizer',
    name: 'Keyword Optimizer',
    category: 'ats',
    colors: ['gray', 'blue'],
    layout: 'single-column',
    preview: '/templates/keyword-optimizer.png',
    description: 'Dense, keyword-forward layout designed to match job description scans',
    features: ['Core competencies block', 'Skills-first ordering', 'Machine-readable fonts'],
    bestFor: ['Career changers', 'Recruitment-heavy industries', 'Remote applications'],
    atsScore: 98,
    popularity: 4,
    isPremium: false,
    config: {
      type: 'minimal', font: 'roboto', colorScheme: 'gray', fontSize: 'small', spacing: 'compact',
      showIcons: false, showBorders: false,
      sections: { experience: true, education: true, skills: true, projects: false, certifications: true, languages: false },
      layout_type: 'single-column',
    },
  },
  {
    id: 'scanner-safe',
    name: 'Scanner Safe',
    category: 'ats',
    colors: ['black', 'gray'],
    layout: 'single-column',
    preview: '/templates/scanner-safe.png',
    description: 'The safest possible structure for resumes screened by older ATS software',
    features: ['Single font', 'No icons or graphics', 'Left-aligned only'],
    bestFor: ['Enterprise applications', 'Older application portals', 'Federal jobs'],
    atsScore: 99,
    popularity: 3,
    isPremium: false,
    config: {
      type: 'minimal', font: 'calibri', colorScheme: 'gray', fontSize: 'medium', spacing: 'normal',
      showIcons: false, showBorders: false,
      sections: { experience: true, education: true, skills: true, projects: false, certifications: false, languages: false },
      layout_type: 'single-column',
    },
  },
];